### ISSUE TITLE
Index with name: obj_id_1 already exists with different options

### ISSUE THREAD

**Issue by theevilbit** [crits/crits_services#155]
When trying to upgrade CRITS from 2015 february version to today's I got the following error while running "./manage.py prep":

Creating indexes (duplicates will be ignored automatically)
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/data/crits/crits/core/management/commands/prep.py", line 26, in handle
    prep_database()
  File "/data/crits/crits/core/management/commands/prep.py", line 173, in prep_database
    prep_indexes()
  File "/data/crits/crits/core/management/commands/prep.py", line 159, in prep_indexes
    create_indexes()
  File "/data/crits/crits/core/management/commands/create_indexes.py", line 144, in create_indexes
    notifications.ensure_index("obj_id", background=True)
  File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 1167, in ensure_index
  File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 1060, in create_index
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 445, in command
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 351, in _command
  File "build/bdist.linux-x86_64/egg/pymongo/helpers.py", line 178, in _check_command_response
pymongo.errors.OperationFailure: command SON([('createIndexes', u'notifications'), ('indexes', [{'background': True, 'name': u'obj_id_1', 'key': SON([('obj_id', 1)])}])]) failed: Index with name: obj_id_1 already exists with different options

**Comment by mgoffin** [comment]
This has nothing to do with crits services, and is fixed by following the UPDATING in core and removing old indexes that need to be rebuilt.

**Comment by theevilbit** [comment]
yep, posted in the wrong place
