### ISSUE TITLE
stix_doc_converter.py can't be run successfully

### ISSUE THREAD

**Issue by johnmccash** [crits/crits_services#77]
When attempting to invoke stix_doc_converter.py, using the syntax:

python manage.py runscript crits_scripts stix_doc_converter -e  -- -i /<path>/stix.xml -o /<folder path> -s <source name>

I get the following error:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/CRITsVirtualEnv/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/data/crits/crits/core/management/commands/runscript.py", line 89, in handle
    script = script_class(username=username)
TypeError: __init__() got an unexpected keyword argument 'username'

I've tried it using other authentication options, but get the same behavior. I'm suspecting the script API may have changed since this was written... Also, it's the only one of the scripts that uses argparse instead of optparse. I don't really speak python, but is this a quick and easy fix? I've got some data I'd like to import that is in STIX 1.0, and uses the STIX_Packages root node, so nothing else I've been able to find will convert it.

Thanks
John

**Comment by dsnellgrove** [comment]
Sounds like that script was not upgraded for the new form of init in 3.0 which passes a username to the service.

**Comment by johnmccash** [comment]
Is that something easy?
